apiVersion: v1
kind: Secret
metadata:
  name: sops-hcvault
data:
  sops.vault-token: aHZzLndOeHBzOGROSjlhdnBuNlBZUUJUdkpUVw==
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/local
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-hcvault
