apiVersion: v1
data:
    password: ENC[AES256_GCM,data:P8go81phOzVTyXoF,iv:oSe0hLk6B9p0XIEgZHlx5898F9eX0cr+VjKg8mUaCds=,tag:j/PXYNNciXL2rgX3DkNszw==,type:str]
    user: ENC[AES256_GCM,data:JJRPW7Z0A0M=,iv:mpt6jg2c3ZvKJzQ2fEW6rmlhjEYPUDw9Q06Ob6pDtqM=,tag:b1o8fFn0Z3JhU+L5n3KJEA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: default
sops:
    hc_vault:
        - vault_address: http://0.0.0.0:8200
          engine_path: transit
          key_name: sops
          created_at: "2026-03-16T09:45:13Z"
          enc: vault:v1:eoTAlFQ7ri0mrImmpNpj17G4ozLjPO0G3H+j+GvCFzcd3z1o/GJQ5lerAWFuIE57SejLslcmGh5YjtFE
    lastmodified: "2026-03-16T09:45:13Z"
    mac: ENC[AES256_GCM,data:XU0ryIFH6LCJlpy8pkfAdSQCTqnt2KZeG67pN566mE26AAMoGw2sQeyT8dNbhhssNxLlbcd/diUuIfctW2B3cGs5L6F7t8CJ8LyJlepKk8OEdYFk8LBb45n7lKAPtU2f4R/9vUzYS8oPN5/7ZA8mc5MpFuLKrPd5kDEWQkDcKIY=,iv:sRahfa5t14NyyO+Q1AN1O1Hw5fRb50ueHsAzst119/g=,tag:N3F9HOVPEoNcAUhH1Q1oEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
